version: '3'

services:
  db:
    container_name: example-db
    image: mysql/mysql-server:8.0.23
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: main
      MYSQL_ROOT_HOST: "%"
